---
# This role installs HAProxy and configures it.

- name: Download and install haproxy
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - haproxy

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  become: yes
  notify: restart haproxy

- name: Start the haproxy service
  become: yes
  service: name=haproxy state=started enabled=yes
