---
- name: user module
  hosts: all
  become: true
  vars:
    myuser: "user01"
    mypassword: "changeme"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"