---
- name: "Setup Databases"
  hosts: dbservers
  become: yes
  roles:
    - role: postgresql
      tags: postgresql
- name: "Setup Application Servers"
  hosts: appservers
  become: yes
  roles:
    - role: jetty
      tags: jetty
- name: "Setup Web Servers"
  hosts: webservers
  become: yes
  roles:
    - role: web
      tags: web
- name: "Setup Load Balancers"
  hosts: lbservers
  become: yes
  roles:
    - role: haproxy
      tags: haproxy
