---
- name: "Setup Databases"
  hosts: dbservers
  become: yes
  roles:
  - postgresql
- name: "Setup Application Servers"
  hosts: appservers
  become: yes
  roles:
  - jetty
- name: "Setup Web Servers"
  hosts: webservers
  become: yes
  roles:
  - web
- name: "Setup Load Balancers"
  hosts: lbservers
  become: yes
  roles:
  - haproxy
