---
- name: restart ssh
  service: name=ssh state=restarted

- name: update hostname
  command: "hostname {{ pizeros_hostname }}"

- name: delete dhcp leases
  file:
     path: /var/lib/dhcp/dhclient.leases
     state: absent
  with_items:
        - /var/lib/dhcp/dhclient.leases
        - /var/lib/dhcpcd5/dhcpcd-eth0.lease
  